version: 2
updates:
  # Update Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Enable automatic rebasing
    rebase-strategy: "auto"
    
  # You can add more package ecosystems as needed, for example:
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   rebase-strategy: "auto"
